spring:
  application:
    name: kewei-ai-agent
  profiles:
    active: local,ollama
  autoconfigure:
    exclude:
      - com.alibaba.cloud.ai.autoconfigure.dashscope.DashScopeAgentAutoConfiguration
      - com.alibaba.cloud.ai.autoconfigure.dashscope.DashScopeChatAutoConfiguration
      - com.alibaba.cloud.ai.autoconfigure.dashscope.DashScopeEmbeddingAutoConfiguration
      - com.alibaba.cloud.ai.autoconfigure.dashscope.DashScopeImageAutoConfiguration
      - com.alibaba.cloud.ai.autoconfigure.dashscope.DashScopeRerankAutoConfiguration
      - com.alibaba.cloud.ai.autoconfigure.dashscope.DashScopeAudioSpeechAutoConfiguration
      - com.alibaba.cloud.ai.autoconfigure.dashscope.DashScopeAudioTranscriptionAutoConfiguration
      - com.alibaba.cloud.ai.autoconfigure.dashscope.DashScopeVideoAutoConfiguration
      - com.alibaba.cloud.ai.autoconfigure.dashscope.DashScopeAsyncToolCallingManagerAutoConfiguration
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen3.5:35b
      embedding:
        options:
          model: mxbai-embed-large:latest
    mcp:
      client:
        annotation-scanner:
          enabled: false
#        sse:
#          connections:
#            server1:
#                url: http://localhost:8129
        stdio:
          servers-configuration: classpath:mcp-servers.json
        request-timeout: 200s

    vectorstore:
      pgvector:
        initialize-schema: true
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1024
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch


server:
  port: 8123
  servlet:
    context-path: /api

# springdoc-openapi ??????
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.kiwi.keweiaiagent.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn

app:
  long-term-memory:
    dir: ${user.dir}/tmp/agent-memory
