package com.kiwi.keweiaiagent.tools;

import org.springframework.ai.tool.annotation.Tool;
import org.springframework.stereotype.Component;

import java.awt.Rectangle;
import java.io.FileOutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.apache.poi.xslf.usermodel.XMLSlideShow;
import org.apache.poi.xslf.usermodel.XSLFNotes;
import org.apache.poi.xslf.usermodel.XSLFSlide;
import org.apache.poi.xslf.usermodel.XSLFTextBox;
import org.apache.poi.xslf.usermodel.XSLFTextParagraph;
import org.apache.poi.xslf.usermodel.XSLFTextRun;

@Component
public class PptWriterTool {

    public record SlideSpec(String title, List<String> bullets, String speakerNotes) {}
    public record PptSpec(String title, String slidesMarkdown, String outputPath) {}

    @Tool(description = """
            在磁盘生成 .pptx 文件。
            输入包含:
            - title: PPT标题
            - slidesMarkdown: 扁平文本格式的页面内容，使用 `## 页面标题` 开头，使用 `- 要点` 表示 bullet，使用 `Notes: 备注内容` 表示演讲备注
            - outputPath: 输出文件路径，必须以 .pptx 结尾
            返回:
            - success: 是否成功
            - path: 生成文件路径
            - slides: 实际总页数（包含标题页）
            - title: PPT标题
            """)
    public Map<String, Object> create_pptx(PptSpec spec) throws Exception {
        validateSpec(spec);
        List<SlideSpec> slides = parseSlides(spec.slidesMarkdown());

        Path out = Path.of(spec.outputPath());
        Path parent = out.getParent();
        if (parent != null) {
            Files.createDirectories(parent);
        }

        try (XMLSlideShow ppt = new XMLSlideShow()) {

            // 1) 标题页
            XSLFSlide titleSlide = ppt.createSlide();

            XSLFTextBox titleBox = titleSlide.createTextBox();
            titleBox.setAnchor(new Rectangle(60, 80, 600, 80));
            titleBox.clearText();

            XSLFTextParagraph titlePara = titleBox.addNewTextParagraph();
            XSLFTextRun titleRun = titlePara.addNewTextRun();
            titleRun.setText(spec.title());
            titleRun.setFontSize(28.0);
            titleRun.setBold(true);

            XSLFTextBox subBox = titleSlide.createTextBox();
            subBox.setAnchor(new Rectangle(60, 180, 600, 40));
            subBox.setText("Generated by PptWriterTools");

            // 2) 内容页
            for (SlideSpec s : slides) {
                XSLFSlide slide = ppt.createSlide();

                // 标题
                XSLFTextBox slideTitleBox = slide.createTextBox();
                slideTitleBox.setAnchor(new Rectangle(40, 30, 640, 50));
                slideTitleBox.clearText();

                XSLFTextParagraph slideTitlePara = slideTitleBox.addNewTextParagraph();
                XSLFTextRun slideTitleRun = slideTitlePara.addNewTextRun();
                slideTitleRun.setText(nonBlankOrDefault(s.title(), "Untitled Slide"));
                slideTitleRun.setFontSize(24.0);
                slideTitleRun.setBold(true);

                // 正文 bullets
                XSLFTextBox bodyBox = slide.createTextBox();
                bodyBox.setAnchor(new Rectangle(60, 100, 620, 320));
                bodyBox.clearText();

                if (s.bullets() != null && !s.bullets().isEmpty()) {
                    for (String bullet : s.bullets()) {
                        if (bullet == null || bullet.isBlank()) {
                            continue;
                        }
                        XSLFTextParagraph p = bodyBox.addNewTextParagraph();
                        p.setBullet(true);
                        XSLFTextRun r = p.addNewTextRun();
                        r.setText(bullet);
                        r.setFontSize(18.0);
                    }
                } else {
                    XSLFTextParagraph p = bodyBox.addNewTextParagraph();
                    XSLFTextRun r = p.addNewTextRun();
                    r.setText("(No content)");
                    r.setFontSize(18.0);
                }

                // speaker notes -> 真正写到备注页
                if (s.speakerNotes() != null && !s.speakerNotes().isBlank()) {
                    XSLFNotes notes = ppt.getNotesSlide(slide);
                    XSLFTextBox notesBox = notes.createTextBox();
                    notesBox.setAnchor(new Rectangle(40, 40, 600, 300));
                    notesBox.setText(s.speakerNotes());
                }
            }

            try (FileOutputStream fos = new FileOutputStream(out.toFile())) {
                ppt.write(fos);
            }
        }

        int totalSlides = 1 + slides.size();

        return Map.of(
                "success", true,
                "path", out.toAbsolutePath().toString(),
                "slides", totalSlides,
                "title", spec.title()
        );
    }

    private void validateSpec(PptSpec spec) {
        if (spec == null) {
            throw new IllegalArgumentException("spec must not be null");
        }
        if (spec.title() == null || spec.title().isBlank()) {
            throw new IllegalArgumentException("title must not be blank");
        }
        if (spec.slidesMarkdown() == null || spec.slidesMarkdown().isBlank()) {
            throw new IllegalArgumentException("slidesMarkdown must not be blank");
        }
        if (spec.outputPath() == null || spec.outputPath().isBlank()) {
            throw new IllegalArgumentException("outputPath must not be blank");
        }
        if (!spec.outputPath().toLowerCase().endsWith(".pptx")) {
            throw new IllegalArgumentException("outputPath must end with .pptx");
        }
    }

    private List<SlideSpec> parseSlides(String slidesMarkdown) {
        List<SlideSpec> slides = new ArrayList<>();
        String currentTitle = null;
        List<String> currentBullets = new ArrayList<>();
        String currentNotes = null;

        for (String rawLine : slidesMarkdown.split("\\R")) {
            String line = rawLine == null ? "" : rawLine.trim();
            if (line.isEmpty()) {
                continue;
            }
            if (line.startsWith("## ")) {
                if (currentTitle != null) {
                    slides.add(new SlideSpec(currentTitle, List.copyOf(currentBullets), currentNotes));
                }
                currentTitle = line.substring(3).trim();
                currentBullets = new ArrayList<>();
                currentNotes = null;
                continue;
            }
            if (line.startsWith("- ")) {
                currentBullets.add(line.substring(2).trim());
                continue;
            }
            if (line.regionMatches(true, 0, "Notes:", 0, "Notes:".length())) {
                currentNotes = line.substring("Notes:".length()).trim();
                continue;
            }
            if (line.regionMatches(true, 0, "备注:", 0, "备注:".length())) {
                currentNotes = line.substring("备注:".length()).trim();
                continue;
            }
            if (currentTitle == null) {
                currentTitle = line;
                continue;
            }
            currentBullets.add(line);
        }

        if (currentTitle != null) {
            slides.add(new SlideSpec(currentTitle, List.copyOf(currentBullets), currentNotes));
        }
        if (slides.isEmpty()) {
            throw new IllegalArgumentException("slidesMarkdown must contain at least one slide");
        }
        return slides;
    }

    private String nonBlankOrDefault(String value, String defaultValue) {
        return (value == null || value.isBlank()) ? defaultValue : value;
    }
}
